#!/bin/bash

if [ "$1" = "install" ]; then
    echo "Adding RasDash service to systemctl..."
    cat server/rasdash.service | sudo sed "s@\${DIR}@${PWD}@" - > /etc/systemd/system/rasdash.service
    sudo systemctl enable rasdash.service
    echo "Done."
    
elif [ "$1" = "start" ]; then
    echo "Starting RasDash service..."
    sudo systemctl start rasdash.service
    
elif [ "$1" = "stop" ]; then
    echo "Stopping RasDash service..."
    sudo systemctl stop rasdash.service

elif [ "$1" = "restart" ]; then
    echo "Restarting RasDash service..."
    sudo systemctl restart rasdash.service
    
elif [ "$1" = "enable" ]; then
    echo "Enabling RasDash service to start on boot..."
    sudo systemctl enable rasdash.service

elif [ "$1" = "disable" ]; then
    echo "Disabling RasDash service from starting on boot..."
    sudo systemctl disable rasdash.service

elif [ "$1" = "uninstall" ]; then
    echo "Removing RasDash service from systemctl..."
    sudo systemctl stop rasdash.service
    sudo systemctl disable rasdash.service
    sudo rm -f /etc/systemd/system/rasdash.service
    sudo systemctl daemon-reload

elif [ "$1" = "help" ]; then
    echo ""
    echo "./service_manager [option]"
    echo ""
    echo "install     Installs RasDash service and enables start on boot"
    echo "start       Starts RasDash via systemctl (service must be installed)"
    echo "stop        Stops RasDash via systemctl (service must be installed)"
    echo "restart     Restarts RasDash via systemctl (service must be installed)"
    echo "enable      Enables RasDash to start on boot (service must be installed)"
    echo "disable     Disables RasDash from starting on boot (service must be installed)"
    echo "uninstall   Completely removes RasDash service from systemctl"
    echo ""

else
    echo "Invalid option. Options are help, install, uninstall, enable, disable, start, stop, restart."

fi